"""create maintenance_requests and assignments tables

Revision ID: 00900af926d6
Revises: b1ca2ccbcbda
Create Date: 2026-09-01 01:03:02.008527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00900af926d6'
down_revision = 'b1ca2ccbcbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('contractor_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['maintenance_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'contractor_id', name='uq_request_contractor')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignments')
    op.drop_table('maintenance_requests')
    # ### end Alembic commands ###
