"""create payments table

Revision ID: 0e5fc2ebbbe6
Revises: 1eecae4d03d5
Create Date: 2026-09-01 12:42:57.966274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e5fc2ebbbe6'
down_revision = '1eecae4d03d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('month_covered', sa.String(length=7), nullable=False),
    sa.Column('match_status', sa.String(length=20), nullable=False),
    sa.Column('recorded_by', sa.String(length=36), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    # ### end Alembic commands ###
