"""create alerts table

Revision ID: 8f67e2e4ba62
Revises: 0e5fc2ebbbe6
Create Date: 2026-09-01 12:54:30.876053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f67e2e4ba62'
down_revision = '0e5fc2ebbbe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('month_covered', sa.String(length=7), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dismissed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'month_covered', name='uq_unit_month_alert')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('recorded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('recorded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    op.drop_table('alerts')
    # ### end Alembic commands ###
